Socks.Web/Controllers/SockInformationController.cs
using Socks.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Socks.Web.Controllers
{
    public class SockInformationController : BaseController
    {
        public ActionResult GetSockPrice()
        {
            Random rnd = new Random();

            if (DateTime.Now.Subtract(sock.CreationDate) > TimeSpan.FromHours(1))
            {
                sock.Price = sock.Price * rnd.Next(0, 3);
            }

            return View(new SockInformationViewModel()
            {
                Price = sock.Price
            });
        }
    }
}

Socks.Web/Controllers/UserInformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Socks.Web.Models;
using System.Globalization;

namespace Socks.Web.Controllers
{
    public class UserInformationController : BaseController
    {
        public ActionResult GetUserInformation()
        {
            string currentUserId = this.User.Identity.GetUserId();
            var userInfo = this.db.Users.Where(u => u.Id == currentUserId).Select(UserInformationViewModel.ViewModel).ToList();

            return View(new UserInformationViewModel()
            {
                FullName = userInfo[0].FullName,
                Email = userInfo[0].Email,
                RegistrationDate = userInfo[0].RegistrationDate,
                Balance = userInfo[0].Balance
            });
        }
    }
}

Socks.Web/Views/Shared/_Deposit.cshtml
@model Socks.Web.Models.DepositInputModel

@{
    ViewBag.Title = "Deposit";
}

@using (Ajax.BeginForm("DoDeposit", "Home",
                                        new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "user-amount" }))
{
    @Html.AntiForgeryToken();
    <input type="text" id="amount" name="amount" />
    <input type="submit" value="Do Deposit" />
}

Socks.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Socks Store</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Socks", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("User Information", "GetUserInformation", "UserInformation")</li>
                        <li>@Html.ActionLink("Sock Information", "GetSockPrice", "SockInformation")</li>
                        <li>@Html.ActionLink("Deposit", "CreateDepositForm", "Home")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Socks Store</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Socks.Web/Views/Shared/_SockInfo.cshtml
@model Socks.Web.Models.SockInformationViewModel

<div class="container">
    <h2>Sock Price:</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Sock Price</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@string.Format("{0:C}", Model.Price);</td>
            </tr>
        </tbody>
    </table>
</div>

Socks.Web/Views/Shared/_UserInfo.cshtml
@model Socks.Web.Models.UserInformationViewModel

<div class="container">
    <h2>User Information:</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Fullane</th>
                <th>Email</th>
                <th>Registration Date</th>
                <th>Balance</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.FullName</td>
                <td>@Model.Email</td>
                <td>@string.Format("{0:C}", Model.Balance);</td>
            </tr>
        </tbody>
    </table>
</div>